# -*- coding: utf-8 -*-
"""coding.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yuHaa5MYI4-kiMUF8v9I8pnoWFOUC_cQ
"""

a = int(input("What is the value of a = "))
b = int(input("What is the value of b = "))
c = a+b
print(c)